import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';
import typography from '@tailwindcss/typography';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class', // تفعيل Dark Mode باستخدام class
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './vendor/laravel/jetstream/**/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Cairo', ...defaultTheme.fontFamily.sans],
            },
            colors: {
                primary: {
                    DEFAULT: '#5C70E0',
                    50: '#EFF0FB',
                    100: '#DFE1F7',
                    200: '#BFC3EF',
                    300: '#9FA5E7',
                    400: '#7F87DF',
                    500: '#5C70E0',
                    600: '#4A5AB3',
                    700: '#374386',
                    800: '#252D5A',
                    900: '#12162D',
                },
                secondary: {
                    DEFAULT: '#815FE4',
                    50: '#F5F1FD',
                    100: '#EBE3FB',
                    200: '#D7C7F7',
                    300: '#C3ABF3',
                    400: '#AF8FEF',
                    500: '#815FE4',
                    600: '#674CB6',
                    700: '#4D3989',
                    800: '#34265B',
                    900: '#1A132E',
                },
            },
        },
    },

    plugins: [forms, typography],

    safelist: [
        'grid',
        'grid-cols-1',
        'grid-cols-2',
        'grid-cols-3',
        'grid-cols-4',
        'sm:grid-cols-1',
        'sm:grid-cols-2',
        'sm:grid-cols-3',
        'sm:grid-cols-4',
        'md:grid-cols-1',
        'md:grid-cols-2',
        'md:grid-cols-3',
        'md:grid-cols-4',
        'lg:grid-cols-1',
        'lg:grid-cols-2',
        'lg:grid-cols-3',
        'lg:grid-cols-4',
        'xl:grid-cols-1',
        'xl:grid-cols-2',
        'xl:grid-cols-3',
        'xl:grid-cols-4',
        'bg-gradient-to-r',
        'from-primary-500',
        'from-primary-600',
        'from-primary-700',
        'to-primary-600',
        'to-primary-700',
        'to-primary-800',
        'to-secondary-500',
        'from-secondary-400',
        'from-secondary-600',
        'from-secondary-700',
        'to-secondary-600',
        'to-secondary-700',
        'to-secondary-800',
        'bg-secondary-400',
        'bg-secondary-600',
        'bg-secondary-700',
        'bg-secondary-800',
        'via-secondary-50',
        'via-primary-600',
        'from-gray-400',
        'to-gray-500',
        'from-gray-700',
        'to-gray-600',
        // Badge colors for tickets
        'bg-red-100',
        'bg-red-900',
        'text-red-800',
        'text-red-300',
        'border-red-200',
        'border-red-800',
        'bg-purple-100',
        'bg-purple-900',
        'text-purple-800',
        'text-purple-300',
        'border-purple-200',
        'border-purple-800',
        'bg-blue-100',
        'bg-blue-900',
        'text-blue-800',
        'text-blue-300',
        'border-blue-200',
        'border-blue-800',
        'bg-green-100',
        'bg-green-900',
        'text-green-800',
        'text-green-300',
        'border-green-200',
        'border-green-800',
        'bg-yellow-100',
        'bg-yellow-900',
        'text-yellow-800',
        'text-yellow-300',
        'border-yellow-200',
        'border-yellow-800',
        'bg-orange-100',
        'bg-orange-900',
        'text-orange-800',
        'text-orange-300',
        'border-orange-200',
        'border-orange-800',
        // Additional gradient colors
        'from-primary-500',
        'to-primary-600',
        'from-secondary-400',
        'to-secondary-600',
        'via-primary-500',
        'to-secondary-600',
    ],
};
